name: RAK BSP Arduino Build CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository:  RAKWireless/WisBlock-CI 
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: extra libraries
      run: |
        /home/runner/work/RAK-RP-Arduino/RAK-RP-Arduino/bin/arduino-cli lib install SX126x-Arduino
        /home/runner/work/RAK-RP-Arduino/RAK-RP-Arduino/bin/arduino-cli lib install Arduino_LPS22HB
        /home/runner/work/RAK-RP-Arduino/RAK-RP-Arduino/bin/arduino-cli lib install ArduinoRS485
        /home/runner/work/RAK-RP-Arduino/RAK-RP-Arduino/bin/arduino-cli lib install ArduinoModbus
        git clone --quiet https://github.com/sparkfun/SparkFun_SHTC3_Arduino_Library
        mv SparkFun_SHTC3_Arduino_Library /home/runner/Arduino/libraries/SparkFun_SHTC3_Arduino_Library
        git clone --quiet https://github.com/closedcube/ClosedCube_OPT3001_Arduino
        mv ClosedCube_OPT3001_Arduino /home/runner/Arduino/libraries/ClosedCube_OPT3001_Arduino
        git clone --quiet https://github.com/sparkfun/SparkFun_LIS3DH_Arduino_Library
        mv SparkFun_LIS3DH_Arduino_Library /home/runner/Arduino/libraries/SparkFun_LIS3DH_Arduino_Library
        git clone --quiet https://github.com/adafruit/Adafruit_Sensor
        mv Adafruit_Sensor /home/runner/Arduino/libraries/Adafruit_Sensor
        git clone --quiet https://github.com/adafruit/Adafruit_BME680
        mv Adafruit_BME680 /home/runner/Arduino/libraries/Adafruit_BME680
        git clone --quiet https://github.com/BoschSensortec/BSEC-Arduino-library
        mv BSEC-Arduino-library /home/runner/Arduino/libraries/BSEC-Arduino-library
        git clone --quiet https://github.com/adafruit/Adafruit_TCS34725
        mv Adafruit_TCS34725 /home/runner/Arduino/libraries/Adafruit_TCS34725
        git clone --quiet https://github.com/sparkfun/SparkFun_TMP102_Arduino_Library
        mv SparkFun_TMP102_Arduino_Library /home/runner/Arduino/libraries/SparkFun_TMP102_Arduino_Library
        git clone --quiet https://github.com/sparkfun/SparkFun_SGP30_Arduino_Library
        mv SparkFun_SGP30_Arduino_Library /home/runner/Arduino/libraries/SparkFun_SGP30_Arduino_Library
        git clone --quiet https://github.com/neosarchizo/TinyGPS
        mv TinyGPS /home/runner/Arduino/libraries/TinyGPS
        /home/runner/work/RAK-RP-Arduino/RAK-RP-Arduino/bin/arduino-cli lib install U8g2
        /home/runner/work/RAK-RP-Arduino/RAK-RP-Arduino/bin/arduino-cli lib install nRF52_OLED
        git clone --quiet https://github.com/adafruit/Adafruit-GFX-Library
        mv Adafruit-GFX-Library /home/runner/Arduino/libraries/Adafruit-GFX-Library
        git clone --quiet https://github.com/sparkfun/SparkFun_MLX90632_Arduino_Library
        mv SparkFun_MLX90632_Arduino_Library /home/runner/Arduino/libraries/SparkFun_MLX90632_Arduino_Library
        git clone --quiet https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library
        mv SparkFun_u-blox_GNSS_Arduino_Library /home/runner/Arduino/libraries/SparkFun_u-blox_GNSS_Arduino_Library
        git clone --quiet https://github.com/adafruit/Adafruit_FRAM_I2C
        mv Adafruit_FRAM_I2C /home/runner/Arduino/libraries/Adafruit_FRAM_I2C
        git clone --quiet https://github.com/adafruit/Adafruit_SPIFlash
        mv Adafruit_SPIFlash /home/runner/Arduino/libraries/Adafruit_SPIFlash
        git clone --quiet https://github.com/adafruit/SdFat
        mv SdFat /home/runner/Arduino/libraries/SdFat
        git clone --quiet https://github.com/adafruit/Adafruit_LPS2X
        mv Adafruit_LPS2X /home/runner/Arduino/libraries/Adafruit_LPS2X
        git clone --quiet https://github.com/adafruit/Adafruit_EPD
        mv Adafruit_EPD /home/runner/Arduino/libraries/Adafruit_EPD
        git clone --quiet https://github.com/adafruit/Adafruit_BusIO
        mv Adafruit_BusIO /home/runner/Arduino/libraries/Adafruit_BusIO
        
    - name: test platforms
      run: python3 ci/build_platform.py rak11300
